require("__platformer__/data/items.lua")
require("__platformer__/data/prototypes/asteroids/aquilo-asteroid.lua")
require("__platformer__/data/prototypes/asteroids/crudeic-asteroid.lua")
require("__platformer__/data/prototypes/asteroids/fulgora-asteroid.lua")
require("__platformer__/data/prototypes/asteroids/gleba-asteroid.lua")
require("__platformer__/data/prototypes/asteroids/vulcanus-asteroid.lua")
